// Generated by scripts/fetch-landmark-images.ts — do not edit by hand.
// Freely licensed photos from Wikimedia Commons; each must be shown with its author and licence.

export interface LandmarkImage {
  url: string;
  sourceUrl: string;
  author: string;
  license: string;
  licenseUrl?: string;
  article: string;
}

export const LANDMARK_IMAGES: Record<string, LandmarkImage> = {
  "fort-canning-tunnel": {
    "url": "https://thumb.wikimedia.org/wikipedia/commons/thumb/2/22/Fort_Canning_Tunnel_2.JPG/960px-Fort_Canning_Tunnel_2.JPG?utm_source=commons.wikimedia.org&utm_campaign=imageinfo&utm_content=thumbnail",
    "sourceUrl": "https://commons.wikimedia.org/wiki/File:Fort_Canning_Tunnel_2.JPG",
    "author": "SpLoT",
    "license": "CC BY 2.5",
    "licenseUrl": "https://creativecommons.org/licenses/by/2.5",
    "article": "Fort Canning Tunnel"
  },
  "tan-teng-niah-villa": {
    "url": "https://thumb.wikimedia.org/wikipedia/commons/thumb/e/ed/2016_Singapur%2C_Little_India%2C_Ulica_Kerbau%2C_By%C5%82a_rezydencja_Tan_Teng_Niaha_%2802%29.jpg/960px-2016_Singapur%2C_Little_India%2C_Ulica_Kerbau%2C_By%C5%82a_rezydencja_Tan_Teng_Niaha_%2802%29.jpg?utm_source=commons.wikimedia.org&utm_campaign=imageinfo&utm_content=thumbnail",
    "sourceUrl": "https://commons.wikimedia.org/wiki/File:2016_Singapur,_Little_India,_Ulica_Kerbau,_By%C5%82a_rezydencja_Tan_Teng_Niaha_(02).jpg",
    "author": "Marcin Konsek",
    "license": "CC BY-SA 4.0",
    "licenseUrl": "https://creativecommons.org/licenses/by-sa/4.0",
    "article": "House of Tan Teng Niah"
  },
  "koon-seng-shophouses": {
    "url": "https://thumb.wikimedia.org/wikipedia/commons/thumb/2/2a/Colorful_shophouses_and_tree_in_Koon_Seng_Road_Singapore.jpg/960px-Colorful_shophouses_and_tree_in_Koon_Seng_Road_Singapore.jpg?utm_source=commons.wikimedia.org&utm_campaign=imageinfo&utm_content=thumbnail",
    "sourceUrl": "https://commons.wikimedia.org/wiki/File:Colorful_shophouses_and_tree_in_Koon_Seng_Road_Singapore.jpg",
    "author": "Basile Morin",
    "license": "CC BY-SA 4.0",
    "licenseUrl": "https://creativecommons.org/licenses/by-sa/4.0",
    "article": "Commons: Colorful shophouses and tree in Koon Seng Road Singapore.jpg"
  },
  "haw-par-villa": {
    "url": "https://thumb.wikimedia.org/wikipedia/commons/thumb/e/e3/A_walk_in_Haw_Par_Villa_Singapore_%282025%29_-_img_15.jpg/960px-A_walk_in_Haw_Par_Villa_Singapore_%282025%29_-_img_15.jpg?utm_source=commons.wikimedia.org&utm_campaign=imageinfo&utm_content=thumbnail",
    "sourceUrl": "https://commons.wikimedia.org/wiki/File:A_walk_in_Haw_Par_Villa_Singapore_(2025)_-_img_15.jpg",
    "author": "Chainwit.",
    "license": "CC BY 4.0",
    "licenseUrl": "https://creativecommons.org/licenses/by/4.0",
    "article": "Haw Par Villa"
  },
  "kampong-lorong-buangkok": {
    "url": "https://thumb.wikimedia.org/wikipedia/commons/thumb/8/8a/Kampong_Lorong_Buangkok%2C_2026_02.jpg/960px-Kampong_Lorong_Buangkok%2C_2026_02.jpg?utm_source=commons.wikimedia.org&utm_campaign=imageinfo&utm_content=thumbnail",
    "sourceUrl": "https://commons.wikimedia.org/wiki/File:Kampong_Lorong_Buangkok,_2026_02.jpg",
    "author": "Actuall7",
    "license": "CC BY 4.0",
    "licenseUrl": "https://creativecommons.org/licenses/by/4.0",
    "article": "Kampong Lorong Buangkok"
  },
  "sultan-mosque-muscat": {
    "url": "https://thumb.wikimedia.org/wikipedia/commons/thumb/4/44/%281924%29_Sultan_Mosque.jpg/960px-%281924%29_Sultan_Mosque.jpg?utm_source=commons.wikimedia.org&utm_campaign=imageinfo&utm_content=thumbnail",
    "sourceUrl": "https://commons.wikimedia.org/wiki/File:(1924)_Sultan_Mosque.jpg",
    "author": "Thank You (23 Millions+) views",
    "license": "CC BY 2.0",
    "licenseUrl": "https://creativecommons.org/licenses/by/2.0",
    "article": "Commons: (1924) Sultan Mosque.jpg"
  },
  "thian-hock-keng-ann-siang": {
    "url": "https://thumb.wikimedia.org/wikipedia/commons/thumb/c/cc/Singapore_Tempel_Thian_Hock_Keng_1.jpg/960px-Singapore_Tempel_Thian_Hock_Keng_1.jpg?utm_source=commons.wikimedia.org&utm_campaign=imageinfo&utm_content=thumbnail",
    "sourceUrl": "https://commons.wikimedia.org/wiki/File:Singapore_Tempel_Thian_Hock_Keng_1.jpg",
    "author": "Zairon",
    "license": "CC BY-SA 4.0",
    "licenseUrl": "https://creativecommons.org/licenses/by-sa/4.0",
    "article": "Thian Hock Keng Temple"
  },
  "southern-ridges-henderson": {
    "url": "https://thumb.wikimedia.org/wikipedia/commons/thumb/3/31/HendersonWaves-Singapore-externalview-20090220.jpg/960px-HendersonWaves-Singapore-externalview-20090220.jpg?utm_source=commons.wikimedia.org&utm_campaign=imageinfo&utm_content=thumbnail",
    "sourceUrl": "https://commons.wikimedia.org/wiki/File:HendersonWaves-Singapore-externalview-20090220.jpg",
    "author": "Kok Leng Yeo from Singapore.",
    "license": "CC BY 2.0",
    "licenseUrl": "https://creativecommons.org/licenses/by/2.0",
    "article": "Henderson Waves"
  },
  "rail-corridor-truss-bridge": {
    "url": "https://thumb.wikimedia.org/wikipedia/commons/thumb/5/55/Bridging_the_past_and_present.jpg/960px-Bridging_the_past_and_present.jpg?utm_source=commons.wikimedia.org&utm_campaign=imageinfo&utm_content=thumbnail",
    "sourceUrl": "https://commons.wikimedia.org/wiki/File:Bridging_the_past_and_present.jpg",
    "author": "darryl chua",
    "license": "CC BY-SA 4.0",
    "licenseUrl": "https://creativecommons.org/licenses/by-sa/4.0",
    "article": "Bukit Timah Truss Bridge"
  },
  "thomson-nature-park-ruins": {
    "url": "https://thumb.wikimedia.org/wikipedia/commons/thumb/a/a4/Thomson_Nature_Park_2020-08-02.jpg/960px-Thomson_Nature_Park_2020-08-02.jpg?utm_source=commons.wikimedia.org&utm_campaign=imageinfo&utm_content=thumbnail",
    "sourceUrl": "https://commons.wikimedia.org/wiki/File:Thomson_Nature_Park_2020-08-02.jpg",
    "author": "Andreas Ehn",
    "license": "CC0",
    "licenseUrl": "http://creativecommons.org/publicdomain/zero/1.0/deed.en",
    "article": "Thomson Nature Park"
  },
  "sungei-buloh-wetlands": {
    "url": "https://thumb.wikimedia.org/wikipedia/commons/thumb/c/cb/Sungei_Buloh_Wetland_Reserve_Banner.JPG/960px-Sungei_Buloh_Wetland_Reserve_Banner.JPG?utm_source=commons.wikimedia.org&utm_campaign=imageinfo&utm_content=thumbnail",
    "sourceUrl": "https://commons.wikimedia.org/wiki/File:Sungei_Buloh_Wetland_Reserve_Banner.JPG",
    "author": "Thaejas",
    "license": "CC BY-SA 3.0",
    "licenseUrl": "https://creativecommons.org/licenses/by-sa/3.0",
    "article": "Sungei Buloh Wetland Reserve"
  },
  "chek-jawa-ubin": {
    "url": "https://thumb.wikimedia.org/wikipedia/commons/thumb/a/a8/Chek_Jawa%2C_Singapore_%283940295137%29.jpg/960px-Chek_Jawa%2C_Singapore_%283940295137%29.jpg?utm_source=commons.wikimedia.org&utm_campaign=imageinfo&utm_content=thumbnail",
    "sourceUrl": "https://commons.wikimedia.org/wiki/File:Chek_Jawa,_Singapore_(3940295137).jpg",
    "author": "William Cho",
    "license": "CC BY-SA 2.0",
    "licenseUrl": "https://creativecommons.org/licenses/by-sa/2.0",
    "article": "Chek Jawa"
  },
  "changi-point-coastal-walk": {
    "url": "https://thumb.wikimedia.org/wikipedia/commons/thumb/6/6c/Changi_village_-_coastal_track_to_point.jpg/960px-Changi_village_-_coastal_track_to_point.jpg?utm_source=commons.wikimedia.org&utm_campaign=imageinfo&utm_content=thumbnail",
    "sourceUrl": "https://commons.wikimedia.org/wiki/File:Changi_village_-_coastal_track_to_point.jpg",
    "author": "Orderinchaos",
    "license": "CC BY-SA 4.0",
    "licenseUrl": "https://creativecommons.org/licenses/by-sa/4.0",
    "article": "Commons: Changi village - coastal track to point.jpg"
  },
  "stb-national-gallery": {
    "url": "https://thumb.wikimedia.org/wikipedia/commons/thumb/b/b3/Interior_of_the_National_Gallery_Singapore.jpg/960px-Interior_of_the_National_Gallery_Singapore.jpg?utm_source=commons.wikimedia.org&utm_campaign=imageinfo&utm_content=thumbnail",
    "sourceUrl": "https://commons.wikimedia.org/wiki/File:Interior_of_the_National_Gallery_Singapore.jpg",
    "author": "Basile Morin",
    "license": "CC BY-SA 4.0",
    "licenseUrl": "https://creativecommons.org/licenses/by-sa/4.0",
    "article": "National Gallery Singapore"
  },
  "stb-sultan-mosque-masjid-sultan": {
    "url": "https://thumb.wikimedia.org/wikipedia/commons/thumb/9/95/The_facade_of_the_Sultan_Mosque_facing_Bussorah_Street_%28Cropped%29.jpg/960px-The_facade_of_the_Sultan_Mosque_facing_Bussorah_Street_%28Cropped%29.jpg?utm_source=commons.wikimedia.org&utm_campaign=imageinfo&utm_content=thumbnail",
    "sourceUrl": "https://commons.wikimedia.org/wiki/File:The_facade_of_the_Sultan_Mosque_facing_Bussorah_Street_(Cropped).jpg",
    "author": "M. Adrian Jurhami",
    "license": "CC BY 4.0",
    "licenseUrl": "https://creativecommons.org/licenses/by/4.0",
    "article": "Sultan Mosque"
  },
  "stb-sri-mariamman-temple": {
    "url": "https://thumb.wikimedia.org/wikipedia/commons/thumb/6/68/Gopuram_-_Sri_Mariamman_Temple_Singapore_%282023%29_-_img_01.jpg/960px-Gopuram_-_Sri_Mariamman_Temple_Singapore_%282023%29_-_img_01.jpg?utm_source=commons.wikimedia.org&utm_campaign=imageinfo&utm_content=thumbnail",
    "sourceUrl": "https://commons.wikimedia.org/wiki/File:Gopuram_-_Sri_Mariamman_Temple_Singapore_(2023)_-_img_01.jpg",
    "author": "Chainwit.",
    "license": "CC BY-SA 4.0",
    "licenseUrl": "https://creativecommons.org/licenses/by-sa/4.0",
    "article": "Sri Mariamman Temple, Singapore"
  },
  "stb-armenian-church-in": {
    "url": "https://thumb.wikimedia.org/wikipedia/commons/thumb/2/24/Armenian_Church_of_Saint_Gregory_the_Illuminator_%D5%8D%D5%B8%D6%82%D6%80%D5%A2_%D4%B3%D6%80%D5%AB%D5%A3%D5%B8%D6%80_%D4%BC%D5%B8%D6%82%D5%BD%D5%A1%D5%BE%D5%B8%D6%80%D5%AB%D5%B9_%D5%A5%D5%AF%D5%A5%D5%B2%D5%A5%D6%81%D5%AB_%28%D5%8D%D5%AB%D5%B6%D5%A3%D5%A1%D5%BA%D5%B8%D6%82%D6%80%29_01.jpg/960px-Armenian_Church_of_Saint_Gregory_the_Illuminator_%D5%8D%D5%B8%D6%82%D6%80%D5%A2_%D4%B3%D6%80%D5%AB%D5%A3%D5%B8%D6%80_%D4%BC%D5%B8%D6%82%D5%BD%D5%A1%D5%BE%D5%B8%D6%80%D5%AB%D5%B9_%D5%A5%D5%AF%D5%A5%D5%B2%D5%A5%D6%81%D5%AB_%28%D5%8D%D5%AB%D5%B6%D5%A3%D5%A1%D5%BA%D5%B8%D6%82%D6%80%29_01.jpg?utm_source=commons.wikimedia.org&utm_campaign=imageinfo&utm_content=thumbnail",
    "sourceUrl": "https://commons.wikimedia.org/wiki/File:Armenian_Church_of_Saint_Gregory_the_Illuminator_%D5%8D%D5%B8%D6%82%D6%80%D5%A2_%D4%B3%D6%80%D5%AB%D5%A3%D5%B8%D6%80_%D4%BC%D5%B8%D6%82%D5%BD%D5%A1%D5%BE%D5%B8%D6%80%D5%AB%D5%B9_%D5%A5%D5%AF%D5%A5%D5%B2%D5%A5%D6%81%D5%AB_(%D5%8D%D5%AB%D5%B6%D5%A3%D5%A1%D5%BA%D5%B8%D6%82%D6%80)_01.jpg",
    "author": "Chainwit.",
    "license": "CC BY-SA 4.0",
    "licenseUrl": "https://creativecommons.org/licenses/by-sa/4.0",
    "article": "Armenian Church, Singapore"
  },
  "stb-chijmes": {
    "url": "https://thumb.wikimedia.org/wikipedia/commons/thumb/f/ff/CHIJMES_3%2C_Jan_06.JPG/960px-CHIJMES_3%2C_Jan_06.JPG?utm_source=commons.wikimedia.org&utm_campaign=imageinfo&utm_content=thumbnail",
    "sourceUrl": "https://commons.wikimedia.org/wiki/File:CHIJMES_3,_Jan_06.JPG",
    "author": "Unknown author",
    "license": "CC BY-SA 3.0",
    "licenseUrl": "http://creativecommons.org/licenses/by-sa/3.0/",
    "article": "CHIJMES"
  },
  "stb-st-andrew-s-cathedral": {
    "url": "https://thumb.wikimedia.org/wikipedia/commons/thumb/1/1c/Saint_Andrew%27s_Cathedral%2C_Singapore_-_20090911.jpg/960px-Saint_Andrew%27s_Cathedral%2C_Singapore_-_20090911.jpg?utm_source=commons.wikimedia.org&utm_campaign=imageinfo&utm_content=thumbnail",
    "sourceUrl": "https://commons.wikimedia.org/wiki/File:Saint_Andrew%27s_Cathedral,_Singapore_-_20090911.jpg",
    "author": "Someformofhuman.",
    "license": "CC BY-SA 3.0",
    "licenseUrl": "https://creativecommons.org/licenses/by-sa/3.0",
    "article": "St Andrew's Cathedral, Singapore"
  },
  "stb-kreta-ayer-square": {
    "url": "https://thumb.wikimedia.org/wikipedia/commons/thumb/b/b0/Kreta_Ayer_Heritage_Gallery%2C_Singapore_%282025%29_-_img_05.jpg/960px-Kreta_Ayer_Heritage_Gallery%2C_Singapore_%282025%29_-_img_05.jpg?utm_source=commons.wikimedia.org&utm_campaign=imageinfo&utm_content=thumbnail",
    "sourceUrl": "https://commons.wikimedia.org/wiki/File:Kreta_Ayer_Heritage_Gallery,_Singapore_(2025)_-_img_05.jpg",
    "author": "Chainwit.",
    "license": "CC BY 4.0",
    "licenseUrl": "https://creativecommons.org/licenses/by/4.0",
    "article": "Commons: Kreta Ayer Heritage Gallery, Singapore (2025) - img 05.jpg"
  },
  "stb-chinatown-food-street": {
    "url": "https://thumb.wikimedia.org/wikipedia/commons/thumb/2/2c/2016_Singapur%2C_Chinatown%2C_Ulica_Smitha_-_Chinatown_Food_Street_%2805%29.jpg/960px-2016_Singapur%2C_Chinatown%2C_Ulica_Smitha_-_Chinatown_Food_Street_%2805%29.jpg?utm_source=commons.wikimedia.org&utm_campaign=imageinfo&utm_content=thumbnail",
    "sourceUrl": "https://commons.wikimedia.org/wiki/File:2016_Singapur,_Chinatown,_Ulica_Smitha_-_Chinatown_Food_Street_(05).jpg",
    "author": "Marcin Konsek",
    "license": "CC BY-SA 4.0",
    "licenseUrl": "https://creativecommons.org/licenses/by-sa/4.0",
    "article": "Commons: 2016 Singapur, Chinatown, Ulica Smitha - Chinatown Food Street (05).jpg"
  },
  "stb-thian-hock-keng-temple": {
    "url": "https://thumb.wikimedia.org/wikipedia/commons/thumb/c/cc/Singapore_Tempel_Thian_Hock_Keng_1.jpg/960px-Singapore_Tempel_Thian_Hock_Keng_1.jpg?utm_source=commons.wikimedia.org&utm_campaign=imageinfo&utm_content=thumbnail",
    "sourceUrl": "https://commons.wikimedia.org/wiki/File:Singapore_Tempel_Thian_Hock_Keng_1.jpg",
    "author": "Zairon",
    "license": "CC BY-SA 4.0",
    "licenseUrl": "https://creativecommons.org/licenses/by-sa/4.0",
    "article": "Thian Hock Keng Temple"
  },
  "stb-capitol-building": {
    "url": "https://thumb.wikimedia.org/wikipedia/commons/thumb/d/df/Capitol_Building%2C_Singapore_%28130948%29.jpg/960px-Capitol_Building%2C_Singapore_%28130948%29.jpg?utm_source=commons.wikimedia.org&utm_campaign=imageinfo&utm_content=thumbnail",
    "sourceUrl": "https://commons.wikimedia.org/wiki/File:Capitol_Building,_Singapore_(130948).jpg",
    "author": "Moheen Reeyad",
    "license": "CC BY-SA 4.0",
    "licenseUrl": "https://creativecommons.org/licenses/by-sa/4.0",
    "article": "Commons: Capitol Building, Singapore (130948).jpg"
  },
  "stb-esplanade-theatre": {
    "url": "https://thumb.wikimedia.org/wikipedia/commons/thumb/f/f3/Esplanade_Theatre%2C_Singapore_%282337436440%29.jpg/960px-Esplanade_Theatre%2C_Singapore_%282337436440%29.jpg?utm_source=commons.wikimedia.org&utm_campaign=imageinfo&utm_content=thumbnail",
    "sourceUrl": "https://commons.wikimedia.org/wiki/File:Esplanade_Theatre,_Singapore_(2337436440).jpg",
    "author": "yeowatzup",
    "license": "CC BY 2.0",
    "licenseUrl": "https://creativecommons.org/licenses/by/2.0",
    "article": "Commons: Esplanade Theatre, Singapore (2337436440).jpg"
  },
  "stb-gardens-by-the-bay": {
    "url": "https://thumb.wikimedia.org/wikipedia/commons/thumb/5/5d/Supertree_Grove%2C_Gardens_by_the_Bay%2C_Singapore_-_20120712-02.jpg/960px-Supertree_Grove%2C_Gardens_by_the_Bay%2C_Singapore_-_20120712-02.jpg?utm_source=commons.wikimedia.org&utm_campaign=imageinfo&utm_content=thumbnail",
    "sourceUrl": "https://commons.wikimedia.org/wiki/File:Supertree_Grove,_Gardens_by_the_Bay,_Singapore_-_20120712-02.jpg",
    "author": "Shiny Things.",
    "license": "CC BY 2.0",
    "licenseUrl": "https://creativecommons.org/licenses/by/2.0",
    "article": "Gardens by the Bay"
  },
  "stb-the-interlace": {
    "url": "https://thumb.wikimedia.org/wikipedia/commons/thumb/6/66/The_Interlace_Singapore.jpg/960px-The_Interlace_Singapore.jpg?utm_source=commons.wikimedia.org&utm_campaign=imageinfo&utm_content=thumbnail",
    "sourceUrl": "https://commons.wikimedia.org/wiki/File:The_Interlace_Singapore.jpg",
    "author": "kallerna",
    "license": "CC BY-SA 4.0",
    "licenseUrl": "https://creativecommons.org/licenses/by-sa/4.0",
    "article": "The Interlace"
  },
  "stb-parkroyal-on-pickering": {
    "url": "https://thumb.wikimedia.org/wikipedia/commons/thumb/4/4b/Parkroyal_on_Pickering_%288579805153%29.crop.jpg/960px-Parkroyal_on_Pickering_%288579805153%29.crop.jpg?utm_source=commons.wikimedia.org&utm_campaign=imageinfo&utm_content=thumbnail",
    "sourceUrl": "https://commons.wikimedia.org/wiki/File:Parkroyal_on_Pickering_(8579805153).crop.jpg",
    "author": "Erwin Soo from Singapore, Singapore",
    "license": "CC BY 2.0",
    "licenseUrl": "https://creativecommons.org/licenses/by/2.0",
    "article": "Parkroyal Collection Pickering"
  },
  "stb-lasalle-college-of-the-arts": {
    "url": "https://thumb.wikimedia.org/wikipedia/commons/thumb/a/ae/Brother_Joseph_McNally_Gallery%2C_LASALLE_College_of_the_Arts%2C_Singapore_-_20140905.jpg/960px-Brother_Joseph_McNally_Gallery%2C_LASALLE_College_of_the_Arts%2C_Singapore_-_20140905.jpg?utm_source=commons.wikimedia.org&utm_campaign=imageinfo&utm_content=thumbnail",
    "sourceUrl": "https://commons.wikimedia.org/wiki/File:Brother_Joseph_McNally_Gallery,_LASALLE_College_of_the_Arts,_Singapore_-_20140905.jpg",
    "author": "Smuconlaw",
    "license": "CC BY-SA 4.0",
    "licenseUrl": "https://creativecommons.org/licenses/by-sa/4.0",
    "article": "Commons: Brother Joseph McNally Gallery, LASALLE College of the Arts, Singapore - 20140905.jpg"
  },
  "stb-kranji-war-memorial-landmark-in": {
    "url": "https://thumb.wikimedia.org/wikipedia/commons/thumb/b/b2/Rear_view_of_the_Cross_of_Sacrifice_at_Kranji_War_Memorial_in_September_2015.jpg/960px-Rear_view_of_the_Cross_of_Sacrifice_at_Kranji_War_Memorial_in_September_2015.jpg?utm_source=commons.wikimedia.org&utm_campaign=imageinfo&utm_content=thumbnail",
    "sourceUrl": "https://commons.wikimedia.org/wiki/File:Rear_view_of_the_Cross_of_Sacrifice_at_Kranji_War_Memorial_in_September_2015.jpg",
    "author": "Nick-D",
    "license": "CC BY-SA 4.0",
    "licenseUrl": "https://creativecommons.org/licenses/by-sa/4.0",
    "article": "Commons: Rear view of the Cross of Sacrifice at Kranji War Memorial in September 2015.jpg"
  },
  "stb-indian-national-army-ina-monument-in": {
    "url": "https://thumb.wikimedia.org/wikipedia/commons/thumb/5/59/Former_Indian_National_Army_Monument.JPG/960px-Former_Indian_National_Army_Monument.JPG?utm_source=commons.wikimedia.org&utm_campaign=imageinfo&utm_content=thumbnail",
    "sourceUrl": "https://commons.wikimedia.org/wiki/File:Former_Indian_National_Army_Monument.JPG",
    "author": "Terence Ong",
    "license": "CC BY 2.5",
    "licenseUrl": "https://creativecommons.org/licenses/by/2.5",
    "article": "Former Indian National Army Monument"
  },
  "stb-reflections-at-bukit-chandu-singapore-war-memorial": {
    "url": "https://upload.wikimedia.org/wikipedia/commons/0/0b/ReflectionsatBukitChandu-Singapore-20070809.jpg?utm_source=commons.wikimedia.org&utm_campaign=imageinfo&utm_content=thumbnail_unscaled",
    "sourceUrl": "https://commons.wikimedia.org/wiki/File:ReflectionsatBukitChandu-Singapore-20070809.jpg",
    "author": "Aldwin Teo at en.wikipedia.",
    "license": "CC BY-SA 3.0",
    "licenseUrl": "https://creativecommons.org/licenses/by-sa/3.0",
    "article": "Reflections at Bukit Chandu"
  },
  "stb-the-cenotaph-a-singapore-war-memorial-landmark": {
    "url": "https://thumb.wikimedia.org/wikipedia/commons/thumb/8/80/Singapore_The-Cenotaph-01.jpg/960px-Singapore_The-Cenotaph-01.jpg?utm_source=commons.wikimedia.org&utm_campaign=imageinfo&utm_content=thumbnail",
    "sourceUrl": "https://commons.wikimedia.org/wiki/File:Singapore_The-Cenotaph-01.jpg",
    "author": "CEphoto, Uwe Aranas",
    "license": "CC BY-SA 4.0",
    "licenseUrl": "https://creativecommons.org/licenses/by-sa/4.0",
    "article": "The Cenotaph, Singapore"
  },
  "stb-the-civilian-war-memorial-park-in": {
    "url": "https://thumb.wikimedia.org/wikipedia/commons/thumb/7/7d/Civilian_War_Memorial_2019.jpg/960px-Civilian_War_Memorial_2019.jpg?utm_source=commons.wikimedia.org&utm_campaign=imageinfo&utm_content=thumbnail",
    "sourceUrl": "https://commons.wikimedia.org/wiki/File:Civilian_War_Memorial_2019.jpg",
    "author": "Deoma12",
    "license": "CC BY-SA 4.0",
    "licenseUrl": "https://creativecommons.org/licenses/by-sa/4.0",
    "article": "Civilian War Memorial"
  },
  "stb-sri-veeramakaliamman-temple": {
    "url": "https://thumb.wikimedia.org/wikipedia/commons/thumb/2/29/2016_Singapur%2C_Little_India%2C_%C5%9Awi%C4%85tynia_Sri_Veeramakaliamman_%2801%29.jpg/960px-2016_Singapur%2C_Little_India%2C_%C5%9Awi%C4%85tynia_Sri_Veeramakaliamman_%2801%29.jpg?utm_source=commons.wikimedia.org&utm_campaign=imageinfo&utm_content=thumbnail",
    "sourceUrl": "https://commons.wikimedia.org/wiki/File:2016_Singapur,_Little_India,_%C5%9Awi%C4%85tynia_Sri_Veeramakaliamman_(01).jpg",
    "author": "Marcin Konsek",
    "license": "CC BY-SA 4.0",
    "licenseUrl": "https://creativecommons.org/licenses/by-sa/4.0",
    "article": "Commons: 2016 Singapur, Little India, Świątynia Sri Veeramakaliamman (01).jpg"
  },
  "stb-maghain-aboth-synagogue": {
    "url": "https://thumb.wikimedia.org/wikipedia/commons/thumb/c/c1/Maghain_Aboth_Synagogue.jpg/960px-Maghain_Aboth_Synagogue.jpg?utm_source=commons.wikimedia.org&utm_campaign=imageinfo&utm_content=thumbnail",
    "sourceUrl": "https://commons.wikimedia.org/wiki/File:Maghain_Aboth_Synagogue.jpg",
    "author": "Gaurav.",
    "license": "CC BY-SA 3.0",
    "licenseUrl": "https://creativecommons.org/licenses/by-sa/3.0",
    "article": "Maghain Aboth Synagogue"
  },
  "stb-old-supreme-court": {
    "url": "https://thumb.wikimedia.org/wikipedia/commons/thumb/1/17/Former_Supreme_Court%2C_Singapore_%281559763572%29.jpg/960px-Former_Supreme_Court%2C_Singapore_%281559763572%29.jpg?utm_source=commons.wikimedia.org&utm_campaign=imageinfo&utm_content=thumbnail",
    "sourceUrl": "https://commons.wikimedia.org/wiki/File:Former_Supreme_Court,_Singapore_(1559763572).jpg",
    "author": "yeowatzup",
    "license": "CC BY 2.0",
    "licenseUrl": "https://creativecommons.org/licenses/by/2.0",
    "article": "Commons: Former Supreme Court, Singapore (1559763572).jpg"
  },
  "stb-lau-pa-sat": {
    "url": "https://thumb.wikimedia.org/wikipedia/commons/thumb/5/5d/Lau_Pa_Sat_Singapore_2.jpg/960px-Lau_Pa_Sat_Singapore_2.jpg?utm_source=commons.wikimedia.org&utm_campaign=imageinfo&utm_content=thumbnail",
    "sourceUrl": "https://commons.wikimedia.org/wiki/File:Lau_Pa_Sat_Singapore_2.jpg",
    "author": "kallerna",
    "license": "CC BY-SA 4.0",
    "licenseUrl": "https://creativecommons.org/licenses/by-sa/4.0",
    "article": "Lau Pa Sat"
  },
  "stb-malay-heritage-centre": {
    "url": "https://thumb.wikimedia.org/wikipedia/commons/thumb/c/c8/Malay_Heritage_Centre%2C_2012.jpg/960px-Malay_Heritage_Centre%2C_2012.jpg?utm_source=commons.wikimedia.org&utm_campaign=imageinfo&utm_content=thumbnail",
    "sourceUrl": "https://commons.wikimedia.org/wiki/File:Malay_Heritage_Centre,_2012.jpg",
    "author": "Elisa.rolle",
    "license": "CC BY-SA 4.0",
    "licenseUrl": "https://creativecommons.org/licenses/by-sa/4.0",
    "article": "Malay Heritage Centre"
  },
  "stb-peranakan-museum-singapore-history-culture": {
    "url": "https://thumb.wikimedia.org/wikipedia/commons/thumb/4/47/Peranakan_Museum_%28Old_Tao_Nan_School%29%2C_August_2024.jpg/960px-Peranakan_Museum_%28Old_Tao_Nan_School%29%2C_August_2024.jpg?utm_source=commons.wikimedia.org&utm_campaign=imageinfo&utm_content=thumbnail",
    "sourceUrl": "https://commons.wikimedia.org/wiki/File:Peranakan_Museum_(Old_Tao_Nan_School),_August_2024.jpg",
    "author": "GoAheadFan95",
    "license": "CC BY-SA 4.0",
    "licenseUrl": "https://creativecommons.org/licenses/by-sa/4.0",
    "article": "Peranakan Museum"
  },
  "stb-raffles": {
    "url": "https://thumb.wikimedia.org/wikipedia/commons/thumb/8/89/Wikimania_Singapore_2023_118.jpg/960px-Wikimania_Singapore_2023_118.jpg?utm_source=commons.wikimedia.org&utm_campaign=imageinfo&utm_content=thumbnail",
    "sourceUrl": "https://commons.wikimedia.org/wiki/File:Wikimania_Singapore_2023_118.jpg",
    "author": "Anthere",
    "license": "CC BY-SA 4.0",
    "licenseUrl": "https://creativecommons.org/licenses/by-sa/4.0",
    "article": "Raffles Hotel"
  },
  "stb-gillman-barracks-yoursingapore": {
    "url": "https://thumb.wikimedia.org/wikipedia/commons/thumb/4/47/Gillman_Barracks_today_%282017%29.jpg/960px-Gillman_Barracks_today_%282017%29.jpg?utm_source=commons.wikimedia.org&utm_campaign=imageinfo&utm_content=thumbnail",
    "sourceUrl": "https://commons.wikimedia.org/wiki/File:Gillman_Barracks_today_(2017).jpg",
    "author": "Estherkhm",
    "license": "CC BY-SA 4.0",
    "licenseUrl": "https://creativecommons.org/licenses/by-sa/4.0",
    "article": "Gillman Barracks"
  },
  "stb-artscience-museum": {
    "url": "https://thumb.wikimedia.org/wikipedia/commons/thumb/f/f3/ArtScience_Museum%2C_Marina_Bay_Sands%2C_Singapore.jpg/960px-ArtScience_Museum%2C_Marina_Bay_Sands%2C_Singapore.jpg?utm_source=commons.wikimedia.org&utm_campaign=imageinfo&utm_content=thumbnail",
    "sourceUrl": "https://commons.wikimedia.org/wiki/File:ArtScience_Museum,_Marina_Bay_Sands,_Singapore.jpg",
    "author": "Basile Morin",
    "license": "CC BY-SA 4.0",
    "licenseUrl": "https://creativecommons.org/licenses/by-sa/4.0",
    "article": "ArtScience Museum"
  },
  "stb-sam-at-8q-singapore-art-museum": {
    "url": "https://thumb.wikimedia.org/wikipedia/commons/thumb/c/c3/8QSamMain.jpg/960px-8QSamMain.jpg?utm_source=commons.wikimedia.org&utm_campaign=imageinfo&utm_content=thumbnail",
    "sourceUrl": "https://commons.wikimedia.org/wiki/File:8QSamMain.jpg",
    "author": "8Q SAM; originally uploaded by Marcus Lim at en.wikipedia.",
    "license": "CC BY-SA 3.0",
    "licenseUrl": "https://creativecommons.org/licenses/by-sa/3.0",
    "article": "SAM at 8Q"
  },
  "stb-jamae-mosque-masjid-chulia": {
    "url": "https://thumb.wikimedia.org/wikipedia/commons/thumb/b/bb/Masjid_Jamae_%28Chulia%29%2C_Singapore%3B_October_2016.jpg/960px-Masjid_Jamae_%28Chulia%29%2C_Singapore%3B_October_2016.jpg?utm_source=commons.wikimedia.org&utm_campaign=imageinfo&utm_content=thumbnail",
    "sourceUrl": "https://commons.wikimedia.org/wiki/File:Masjid_Jamae_(Chulia),_Singapore;_October_2016.jpg",
    "author": "xiquinhosilva from Cacau",
    "license": "CC BY 2.0",
    "licenseUrl": "https://creativecommons.org/licenses/by/2.0",
    "article": "Commons: Masjid Jamae (Chulia), Singapore; October 2016.jpg"
  },
  "stb-singapore-flyer": {
    "url": "https://thumb.wikimedia.org/wikipedia/commons/thumb/7/79/Singapore_Flyer_20250903.jpg/960px-Singapore_Flyer_20250903.jpg?utm_source=commons.wikimedia.org&utm_campaign=imageinfo&utm_content=thumbnail",
    "sourceUrl": "https://commons.wikimedia.org/wiki/File:Singapore_Flyer_20250903.jpg",
    "author": "DvTor8303",
    "license": "CC0",
    "licenseUrl": "http://creativecommons.org/publicdomain/zero/1.0/deed.en",
    "article": "Singapore Flyer"
  },
  "stb-marina-bay-sands": {
    "url": "https://thumb.wikimedia.org/wikipedia/commons/thumb/c/c7/Marina_Bay_Sands_%28I%29.jpg/960px-Marina_Bay_Sands_%28I%29.jpg?utm_source=commons.wikimedia.org&utm_campaign=imageinfo&utm_content=thumbnail",
    "sourceUrl": "https://commons.wikimedia.org/wiki/File:Marina_Bay_Sands_(I).jpg",
    "author": "This Photo was taken by Supanut Arunoprayote. Feel free to use any of my images, but please mention me as the author and may send me a message. (สามารถใช้ภาพได้อิสระ แต่กรุณาใส่เครดิตผู้ถ่ายและอาจส่งข้อความบอกกล่าวด้วย) Please do not upload an updated image here without consultation with the Author. The author would like to make corrections only at his own source. This ensures that the changes are preserved.Please if you think that any changes should be required, please inform the author.Otherwise you can upload a new image with a new name. Please use one of the templates derivative or extract.",
    "license": "CC BY 4.0",
    "licenseUrl": "https://creativecommons.org/licenses/by/4.0",
    "article": "Marina Bay Sands"
  },
  "stb-marina-barrage": {
    "url": "https://thumb.wikimedia.org/wikipedia/commons/thumb/6/60/Marina_Barrage_Closeup_300522.jpg/960px-Marina_Barrage_Closeup_300522.jpg?utm_source=commons.wikimedia.org&utm_campaign=imageinfo&utm_content=thumbnail",
    "sourceUrl": "https://commons.wikimedia.org/wiki/File:Marina_Barrage_Closeup_300522.jpg",
    "author": "Bob Tan",
    "license": "CC BY-SA 4.0",
    "licenseUrl": "https://creativecommons.org/licenses/by-sa/4.0",
    "article": "Marina Barrage"
  },
  "stb-henderson-waves-bridge": {
    "url": "https://thumb.wikimedia.org/wikipedia/commons/thumb/3/31/HendersonWaves-Singapore-externalview-20090220.jpg/960px-HendersonWaves-Singapore-externalview-20090220.jpg?utm_source=commons.wikimedia.org&utm_campaign=imageinfo&utm_content=thumbnail",
    "sourceUrl": "https://commons.wikimedia.org/wiki/File:HendersonWaves-Singapore-externalview-20090220.jpg",
    "author": "Kok Leng Yeo from Singapore.",
    "license": "CC BY 2.0",
    "licenseUrl": "https://creativecommons.org/licenses/by/2.0",
    "article": "Henderson Waves"
  },
  "stb-pinnacle-duxton": {
    "url": "https://thumb.wikimedia.org/wikipedia/commons/thumb/f/f3/Pinnacle%40Duxton%2C_Singapore_-_20100101.jpg/960px-Pinnacle%40Duxton%2C_Singapore_-_20100101.jpg?utm_source=commons.wikimedia.org&utm_campaign=imageinfo&utm_content=thumbnail",
    "sourceUrl": "https://commons.wikimedia.org/wiki/File:Pinnacle@Duxton,_Singapore_-_20100101.jpg",
    "author": "Someformofhuman.",
    "license": "CC BY-SA 3.0",
    "licenseUrl": "https://creativecommons.org/licenses/by-sa/3.0",
    "article": "The Pinnacle@Duxton"
  },
  "stb-hajjah-fatimah-mosque": {
    "url": "https://thumb.wikimedia.org/wikipedia/commons/thumb/c/c8/Masjid_Hajjah_Fatimah%2C_full_exterior_view.jpg/960px-Masjid_Hajjah_Fatimah%2C_full_exterior_view.jpg?utm_source=commons.wikimedia.org&utm_campaign=imageinfo&utm_content=thumbnail",
    "sourceUrl": "https://commons.wikimedia.org/wiki/File:Masjid_Hajjah_Fatimah,_full_exterior_view.jpg",
    "author": "M. Adrian Jurhami",
    "license": "CC BY 4.0",
    "licenseUrl": "https://creativecommons.org/licenses/by/4.0",
    "article": "Masjid Hajjah Fatimah"
  },
  "stb-haw-par-villa-singapore-theme-park": {
    "url": "https://thumb.wikimedia.org/wikipedia/commons/thumb/e/e3/A_walk_in_Haw_Par_Villa_Singapore_%282025%29_-_img_15.jpg/960px-A_walk_in_Haw_Par_Villa_Singapore_%282025%29_-_img_15.jpg?utm_source=commons.wikimedia.org&utm_campaign=imageinfo&utm_content=thumbnail",
    "sourceUrl": "https://commons.wikimedia.org/wiki/File:A_walk_in_Haw_Par_Villa_Singapore_(2025)_-_img_15.jpg",
    "author": "Chainwit.",
    "license": "CC BY 4.0",
    "licenseUrl": "https://creativecommons.org/licenses/by/4.0",
    "article": "Haw Par Villa"
  },
  "stb-hong-san-see-temple": {
    "url": "https://thumb.wikimedia.org/wikipedia/commons/thumb/e/e1/Hong_San_See_3%2C_Oct_06.JPG/960px-Hong_San_See_3%2C_Oct_06.JPG?utm_source=commons.wikimedia.org&utm_campaign=imageinfo&utm_content=thumbnail",
    "sourceUrl": "https://commons.wikimedia.org/wiki/File:Hong_San_See_3,_Oct_06.JPG",
    "author": "Unknown author",
    "license": "CC BY-SA 3.0",
    "licenseUrl": "http://creativecommons.org/licenses/by-sa/3.0/",
    "article": "Hong San See"
  },
  "stb-chinese-heritage-centre": {
    "url": "https://thumb.wikimedia.org/wikipedia/commons/thumb/d/db/NTU_former_administrative_building.jpg/960px-NTU_former_administrative_building.jpg?utm_source=commons.wikimedia.org&utm_campaign=imageinfo&utm_content=thumbnail",
    "sourceUrl": "https://commons.wikimedia.org/wiki/File:NTU_former_administrative_building.jpg",
    "author": "Unknown author",
    "license": "CC BY-SA 3.0",
    "licenseUrl": "http://creativecommons.org/licenses/by-sa/3.0/",
    "article": "Chinese Heritage Centre"
  },
  "stb-kampong-glam-malay-culture-in": {
    "url": "https://thumb.wikimedia.org/wikipedia/commons/thumb/6/6b/Kampong_Glam_aerial_shot_-_20250628_-_RSKY.jpg/960px-Kampong_Glam_aerial_shot_-_20250628_-_RSKY.jpg?utm_source=commons.wikimedia.org&utm_campaign=imageinfo&utm_content=thumbnail",
    "sourceUrl": "https://commons.wikimedia.org/wiki/File:Kampong_Glam_aerial_shot_-_20250628_-_RSKY.jpg",
    "author": "Robert Sim",
    "license": "CC BY-SA 4.0",
    "licenseUrl": "https://creativecommons.org/licenses/by-sa/4.0",
    "article": "Kampong Glam"
  },
  "stb-red-dot-design-museum": {
    "url": "https://thumb.wikimedia.org/wikipedia/commons/thumb/6/6c/Red_Dot_Design_Museum_Singapore.jpg/960px-Red_Dot_Design_Museum_Singapore.jpg?utm_source=commons.wikimedia.org&utm_campaign=imageinfo&utm_content=thumbnail",
    "sourceUrl": "https://commons.wikimedia.org/wiki/File:Red_Dot_Design_Museum_Singapore.jpg",
    "author": "jwalsh from Seattle",
    "license": "CC BY 2.0",
    "licenseUrl": "https://creativecommons.org/licenses/by/2.0",
    "article": "Commons: Red Dot Design Museum Singapore.jpg"
  },
  "stb-singapore-art-museum": {
    "url": "https://thumb.wikimedia.org/wikipedia/commons/thumb/b/b9/Singapore_Art_Museum%2C_2014_%2802%29.JPG/960px-Singapore_Art_Museum%2C_2014_%2802%29.JPG?utm_source=commons.wikimedia.org&utm_campaign=imageinfo&utm_content=thumbnail",
    "sourceUrl": "https://commons.wikimedia.org/wiki/File:Singapore_Art_Museum,_2014_(02).JPG",
    "author": "Bahnfrend",
    "license": "CC BY-SA 4.0",
    "licenseUrl": "https://creativecommons.org/licenses/by-sa/4.0",
    "article": "Commons: Singapore Art Museum, 2014 (02).JPG"
  },
  "stb-esplanade-theatres-on-the-bay": {
    "url": "https://thumb.wikimedia.org/wikipedia/commons/thumb/f/fa/The_Esplanade_%E2%80%93_Theatres_on_the_Bay.jpg/960px-The_Esplanade_%E2%80%93_Theatres_on_the_Bay.jpg?utm_source=commons.wikimedia.org&utm_campaign=imageinfo&utm_content=thumbnail",
    "sourceUrl": "https://commons.wikimedia.org/wiki/File:The_Esplanade_%E2%80%93_Theatres_on_the_Bay.jpg",
    "author": "William Cho",
    "license": "CC BY-SA 2.0",
    "licenseUrl": "https://creativecommons.org/licenses/by-sa/2.0",
    "article": "Esplanade – Theatres on the Bay"
  },
  "stb-national-design-centre": {
    "url": "https://thumb.wikimedia.org/wikipedia/commons/thumb/0/0f/National_Design_Centre%2C_Singapore.jpg/960px-National_Design_Centre%2C_Singapore.jpg?utm_source=commons.wikimedia.org&utm_campaign=imageinfo&utm_content=thumbnail",
    "sourceUrl": "https://commons.wikimedia.org/wiki/File:National_Design_Centre,_Singapore.jpg",
    "author": "ScribblingGeek",
    "license": "CC BY-SA 4.0",
    "licenseUrl": "https://creativecommons.org/licenses/by-sa/4.0",
    "article": "National Design Centre"
  },
  "stb-victoria-theatre": {
    "url": "https://thumb.wikimedia.org/wikipedia/commons/thumb/6/65/Victoria_Theatre_and_Victoria_Concert_Hall%2C_with_54m_high_Clock_Tower.jpg/960px-Victoria_Theatre_and_Victoria_Concert_Hall%2C_with_54m_high_Clock_Tower.jpg?utm_source=commons.wikimedia.org&utm_campaign=imageinfo&utm_content=thumbnail",
    "sourceUrl": "https://commons.wikimedia.org/wiki/File:Victoria_Theatre_and_Victoria_Concert_Hall,_with_54m_high_Clock_Tower.jpg",
    "author": "TTangMonuments",
    "license": "CC BY-SA 4.0",
    "licenseUrl": "https://creativecommons.org/licenses/by-sa/4.0",
    "article": "Victoria Theatre and Concert Hall"
  },
  "stb-nus-university-museum": {
    "url": "https://thumb.wikimedia.org/wikipedia/commons/thumb/a/ad/Royal_portrait_-_Pratistha%2C_NUS_Museum_%28113054%29.jpg/960px-Royal_portrait_-_Pratistha%2C_NUS_Museum_%28113054%29.jpg?utm_source=commons.wikimedia.org&utm_campaign=imageinfo&utm_content=thumbnail",
    "sourceUrl": "https://commons.wikimedia.org/wiki/File:Royal_portrait_-_Pratistha,_NUS_Museum_(113054).jpg",
    "author": "Moheen Reeyad",
    "license": "CC BY-SA 4.0",
    "licenseUrl": "https://creativecommons.org/licenses/by-sa/4.0",
    "article": "Commons: Royal portrait - Pratistha, NUS Museum (113054).jpg"
  },
  "stb-sun-yat-sen-memorial-hall": {
    "url": "https://thumb.wikimedia.org/wikipedia/commons/thumb/f/f7/Sun_Yat_Sen_Nanyang_Memorial_Hall_14-05-2024%2817%29.jpg/960px-Sun_Yat_Sen_Nanyang_Memorial_Hall_14-05-2024%2817%29.jpg?utm_source=commons.wikimedia.org&utm_campaign=imageinfo&utm_content=thumbnail",
    "sourceUrl": "https://commons.wikimedia.org/wiki/File:Sun_Yat_Sen_Nanyang_Memorial_Hall_14-05-2024(17).jpg",
    "author": "LN9267",
    "license": "CC BY-SA 4.0",
    "licenseUrl": "https://creativecommons.org/licenses/by-sa/4.0",
    "article": "Commons: Sun Yat Sen Nanyang Memorial Hall 14-05-2024(17).jpg"
  },
  "stb-asian-civilisations-museum-singapore-museum": {
    "url": "https://thumb.wikimedia.org/wikipedia/commons/thumb/3/3d/Empress_Place_Building_2023-03-22.jpg/960px-Empress_Place_Building_2023-03-22.jpg?utm_source=commons.wikimedia.org&utm_campaign=imageinfo&utm_content=thumbnail",
    "sourceUrl": "https://commons.wikimedia.org/wiki/File:Empress_Place_Building_2023-03-22.jpg",
    "author": "Alexey Komarov",
    "license": "CC BY-SA 4.0",
    "licenseUrl": "https://creativecommons.org/licenses/by-sa/4.0",
    "article": "Asian Civilisations Museum"
  },
  "stb-national-museum-of": {
    "url": "https://thumb.wikimedia.org/wikipedia/commons/thumb/0/09/National_Museum_of_Singapore_during_the_Singapore_Night_Festival_2024_-_01.jpg/960px-National_Museum_of_Singapore_during_the_Singapore_Night_Festival_2024_-_01.jpg?utm_source=commons.wikimedia.org&utm_campaign=imageinfo&utm_content=thumbnail",
    "sourceUrl": "https://commons.wikimedia.org/wiki/File:National_Museum_of_Singapore_during_the_Singapore_Night_Festival_2024_-_01.jpg",
    "author": "Sgconlaw",
    "license": "CC BY-SA 4.0",
    "licenseUrl": "https://creativecommons.org/licenses/by-sa/4.0",
    "article": "Commons: National Museum of Singapore during the Singapore Night Festival 2024 - 01.jpg"
  },
  "stb-the-japanese-cemetery-park": {
    "url": "https://thumb.wikimedia.org/wikipedia/commons/thumb/6/6c/Japanese_Cemetery_Park.jpg/960px-Japanese_Cemetery_Park.jpg?utm_source=commons.wikimedia.org&utm_campaign=imageinfo&utm_content=thumbnail",
    "sourceUrl": "https://commons.wikimedia.org/wiki/File:Japanese_Cemetery_Park.jpg",
    "author": "ProjectManhattan",
    "license": "CC BY-SA 3.0",
    "licenseUrl": "https://creativecommons.org/licenses/by-sa/3.0",
    "article": "Japanese Cemetery Park"
  },
  "stb-raffles-statue-sir-stamford-raffles-landing-site": {
    "url": "https://thumb.wikimedia.org/wikipedia/commons/thumb/c/cb/Sir_stamford_raffles_statue_singapore.jpg/960px-Sir_stamford_raffles_statue_singapore.jpg?utm_source=commons.wikimedia.org&utm_campaign=imageinfo&utm_content=thumbnail",
    "sourceUrl": "https://commons.wikimedia.org/wiki/File:Sir_stamford_raffles_statue_singapore.jpg",
    "author": "Irwan Shah Bin Abdullah / https://ehalal.io/",
    "license": "CC BY 3.0",
    "licenseUrl": "https://creativecommons.org/licenses/by/3.0",
    "article": "Statue of Stamford Raffles"
  },
  "stb-singapore-philatelic-museum": {
    "url": "https://thumb.wikimedia.org/wikipedia/commons/thumb/b/be/Singapore_-_Canning_Rise_-_Singapore_Philatelic_Museum_IMG_9721.jpg/960px-Singapore_-_Canning_Rise_-_Singapore_Philatelic_Museum_IMG_9721.jpg?utm_source=commons.wikimedia.org&utm_campaign=imageinfo&utm_content=thumbnail",
    "sourceUrl": "https://commons.wikimedia.org/wiki/File:Singapore_-_Canning_Rise_-_Singapore_Philatelic_Museum_IMG_9721.jpg",
    "author": "Bjoertvedt",
    "license": "CC BY-SA 4.0",
    "licenseUrl": "https://creativecommons.org/licenses/by-sa/4.0",
    "article": "Commons: Singapore - Canning Rise - Singapore Philatelic Museum IMG 9721.jpg"
  },
  "stb-singapore-city-gallery": {
    "url": "https://thumb.wikimedia.org/wikipedia/commons/thumb/a/a6/Singapore_City_Gallery_%22Central_Area_Model%22_%282025%29_-_img_01.jpg/960px-Singapore_City_Gallery_%22Central_Area_Model%22_%282025%29_-_img_01.jpg?utm_source=commons.wikimedia.org&utm_campaign=imageinfo&utm_content=thumbnail",
    "sourceUrl": "https://commons.wikimedia.org/wiki/File:Singapore_City_Gallery_%22Central_Area_Model%22_(2025)_-_img_01.jpg",
    "author": "Chainwit.",
    "license": "CC BY 4.0",
    "licenseUrl": "https://creativecommons.org/licenses/by/4.0",
    "article": "Singapore City Gallery"
  },
  "stb-changi-museum": {
    "url": "https://upload.wikimedia.org/wikipedia/commons/6/69/Changi_Museum.jpg?utm_source=commons.wikimedia.org&utm_campaign=imageinfo&utm_content=thumbnail_unscaled",
    "sourceUrl": "https://commons.wikimedia.org/wiki/File:Changi_Museum.jpg",
    "author": "Aldwin Teo",
    "license": "CC BY-SA 3.0",
    "licenseUrl": "https://creativecommons.org/licenses/by-sa/3.0",
    "article": "Changi Chapel and Museum"
  },
  "stb-mint-museum-of-toys-singapore-toy-museum": {
    "url": "https://thumb.wikimedia.org/wikipedia/commons/thumb/1/1a/MINT_Museum_of_Toys_in_Singapore.jpg/960px-MINT_Museum_of_Toys_in_Singapore.jpg?utm_source=commons.wikimedia.org&utm_campaign=imageinfo&utm_content=thumbnail",
    "sourceUrl": "https://commons.wikimedia.org/wiki/File:MINT_Museum_of_Toys_in_Singapore.jpg",
    "author": "Sundaymarket38",
    "license": "CC0",
    "licenseUrl": "http://creativecommons.org/publicdomain/zero/1.0/deed.en",
    "article": "Mint Museum of Toys"
  },
  "stb-singapore-science-centre": {
    "url": "https://thumb.wikimedia.org/wikipedia/commons/thumb/5/5e/Entrance_to_Science_Centre_Singapore%2C_2025.jpg/960px-Entrance_to_Science_Centre_Singapore%2C_2025.jpg?utm_source=commons.wikimedia.org&utm_campaign=imageinfo&utm_content=thumbnail",
    "sourceUrl": "https://commons.wikimedia.org/wiki/File:Entrance_to_Science_Centre_Singapore,_2025.jpg",
    "author": "Actuall7",
    "license": "CC BY 4.0",
    "licenseUrl": "https://creativecommons.org/licenses/by/4.0",
    "article": "Science Centre Singapore"
  },
  "stb-fuk-tak-chi-museum-places-of-interest": {
    "url": "https://thumb.wikimedia.org/wikipedia/commons/thumb/3/30/Fuk_Tak_Chi_temple_%2812848380003%29.jpg/960px-Fuk_Tak_Chi_temple_%2812848380003%29.jpg?utm_source=commons.wikimedia.org&utm_campaign=imageinfo&utm_content=thumbnail",
    "sourceUrl": "https://commons.wikimedia.org/wiki/File:Fuk_Tak_Chi_temple_(12848380003).jpg",
    "author": "KimonBerlin",
    "license": "CC BY-SA 2.0",
    "licenseUrl": "https://creativecommons.org/licenses/by-sa/2.0",
    "article": "Commons: Fuk Tak Chi temple (12848380003).jpg"
  },
  "stb-chinese-garden": {
    "url": "https://thumb.wikimedia.org/wikipedia/commons/thumb/0/0f/Chinese_Garden%2C_Singapore_04-12-2024%2874%29.jpg/960px-Chinese_Garden%2C_Singapore_04-12-2024%2874%29.jpg?utm_source=commons.wikimedia.org&utm_campaign=imageinfo&utm_content=thumbnail",
    "sourceUrl": "https://commons.wikimedia.org/wiki/File:Chinese_Garden,_Singapore_04-12-2024(74).jpg",
    "author": "LN9267",
    "license": "CC BY-SA 4.0",
    "licenseUrl": "https://creativecommons.org/licenses/by-sa/4.0",
    "article": "Commons: Chinese Garden, Singapore 04-12-2024(74).jpg"
  },
  "stb-east-coast-park": {
    "url": "https://thumb.wikimedia.org/wikipedia/commons/thumb/8/8b/%28SGP-Singapore%29_East_Coast_Park_Zone_B_2026-01-25.jpg/960px-%28SGP-Singapore%29_East_Coast_Park_Zone_B_2026-01-25.jpg?utm_source=commons.wikimedia.org&utm_campaign=imageinfo&utm_content=thumbnail",
    "sourceUrl": "https://commons.wikimedia.org/wiki/File:(SGP-Singapore)_East_Coast_Park_Zone_B_2026-01-25.jpg",
    "author": "S5A-0043",
    "license": "CC BY 4.0",
    "licenseUrl": "https://creativecommons.org/licenses/by/4.0",
    "article": "East Coast Park"
  },
  "stb-fort-canning-park": {
    "url": "https://thumb.wikimedia.org/wikipedia/commons/thumb/f/f5/Fort_Canning_Park_sign%2C_Singapore_-_20110506.jpg/960px-Fort_Canning_Park_sign%2C_Singapore_-_20110506.jpg?utm_source=commons.wikimedia.org&utm_campaign=imageinfo&utm_content=thumbnail",
    "sourceUrl": "https://commons.wikimedia.org/wiki/File:Fort_Canning_Park_sign,_Singapore_-_20110506.jpg",
    "author": "Michael Coghlan.",
    "license": "CC BY-SA 2.0",
    "licenseUrl": "https://creativecommons.org/licenses/by-sa/2.0",
    "article": "Fort Canning Hill"
  },
  "stb-kusu-island": {
    "url": "https://thumb.wikimedia.org/wikipedia/commons/thumb/1/19/Aerial_perspective_of_Kusu_Island%2C_Singapore._Shot_in_2016.jpg/960px-Aerial_perspective_of_Kusu_Island%2C_Singapore._Shot_in_2016.jpg?utm_source=commons.wikimedia.org&utm_campaign=imageinfo&utm_content=thumbnail",
    "sourceUrl": "https://commons.wikimedia.org/wiki/File:Aerial_perspective_of_Kusu_Island,_Singapore._Shot_in_2016.jpg",
    "author": "Bob Tan",
    "license": "CC BY-SA 4.0",
    "licenseUrl": "https://creativecommons.org/licenses/by-sa/4.0",
    "article": "Kusu Island"
  },
  "stb-jurong-bird-park-attractions-things-to-do": {
    "url": "https://thumb.wikimedia.org/wikipedia/commons/thumb/4/4a/Jurong_Bird_Park_2014.jpg/960px-Jurong_Bird_Park_2014.jpg?utm_source=commons.wikimedia.org&utm_campaign=imageinfo&utm_content=thumbnail",
    "sourceUrl": "https://commons.wikimedia.org/wiki/File:Jurong_Bird_Park_2014.jpg",
    "author": "aamanatullah",
    "license": "CC BY 2.0",
    "licenseUrl": "https://creativecommons.org/licenses/by/2.0",
    "article": "Jurong Bird Park"
  },
  "stb-hortpark": {
    "url": "https://thumb.wikimedia.org/wikipedia/commons/thumb/2/24/Silver_Garden_HortPark_Singapore.jpg/960px-Silver_Garden_HortPark_Singapore.jpg?utm_source=commons.wikimedia.org&utm_campaign=imageinfo&utm_content=thumbnail",
    "sourceUrl": "https://commons.wikimedia.org/wiki/File:Silver_Garden_HortPark_Singapore.jpg",
    "author": "kallerna",
    "license": "CC BY-SA 4.0",
    "licenseUrl": "https://creativecommons.org/licenses/by-sa/4.0",
    "article": "HortPark"
  },
  "stb-adventure-cove-waterpark": {
    "url": "https://thumb.wikimedia.org/wikipedia/commons/thumb/0/0d/Adventure_Cove_Waterpark_in_Sentosa%2C_Singapore.jpg/960px-Adventure_Cove_Waterpark_in_Sentosa%2C_Singapore.jpg?utm_source=commons.wikimedia.org&utm_campaign=imageinfo&utm_content=thumbnail",
    "sourceUrl": "https://commons.wikimedia.org/wiki/File:Adventure_Cove_Waterpark_in_Sentosa,_Singapore.jpg",
    "author": "Haopee G.",
    "license": "CC BY-SA 2.0",
    "licenseUrl": "https://creativecommons.org/licenses/by-sa/2.0",
    "article": "Adventure Cove Waterpark"
  },
  "stb-chinatown-singapore-history-culture": {
    "url": "https://thumb.wikimedia.org/wikipedia/commons/thumb/b/b9/Chinatown_Complex_Food_Centre_%2812849046024%29.jpg/960px-Chinatown_Complex_Food_Centre_%2812849046024%29.jpg?utm_source=commons.wikimedia.org&utm_campaign=imageinfo&utm_content=thumbnail",
    "sourceUrl": "https://commons.wikimedia.org/wiki/File:Chinatown_Complex_Food_Centre_(12849046024).jpg",
    "author": "KimonBerlin",
    "license": "CC BY-SA 2.0",
    "licenseUrl": "https://creativecommons.org/licenses/by-sa/2.0",
    "article": "Commons: Chinatown Complex Food Centre (12849046024).jpg"
  },
  "stb-buddha-tooth-relic-temple-museum-in": {
    "url": "https://thumb.wikimedia.org/wikipedia/commons/thumb/e/e7/BTRTM_as_seen_from_Maxwell_MRT_entrance_%282025%29_-_img_05.jpg/960px-BTRTM_as_seen_from_Maxwell_MRT_entrance_%282025%29_-_img_05.jpg?utm_source=commons.wikimedia.org&utm_campaign=imageinfo&utm_content=thumbnail",
    "sourceUrl": "https://commons.wikimedia.org/wiki/File:BTRTM_as_seen_from_Maxwell_MRT_entrance_(2025)_-_img_05.jpg",
    "author": "Chainwit.",
    "license": "CC BY 4.0",
    "licenseUrl": "https://creativecommons.org/licenses/by/4.0",
    "article": "Buddha Tooth Relic Temple and Museum"
  },
  "stb-labrador-nature-reserve": {
    "url": "https://thumb.wikimedia.org/wikipedia/commons/thumb/4/4c/Labrador_Park_20060419.jpg/960px-Labrador_Park_20060419.jpg?utm_source=commons.wikimedia.org&utm_campaign=imageinfo&utm_content=thumbnail",
    "sourceUrl": "https://commons.wikimedia.org/wiki/File:Labrador_Park_20060419.jpg",
    "author": "Unknown author",
    "license": "CC BY-SA 3.0",
    "licenseUrl": "http://creativecommons.org/licenses/by-sa/3.0/",
    "article": "Labrador Nature Reserve"
  },
  "stb-marina-bay-singapore-attractions-things-to-do": {
    "url": "https://thumb.wikimedia.org/wikipedia/commons/thumb/1/16/Marina_Bay_Singapore-3499.jpg/960px-Marina_Bay_Singapore-3499.jpg?utm_source=commons.wikimedia.org&utm_campaign=imageinfo&utm_content=thumbnail",
    "sourceUrl": "https://commons.wikimedia.org/wiki/File:Marina_Bay_Singapore-3499.jpg",
    "author": "Bijay Chaurasia",
    "license": "CC BY-SA 4.0",
    "licenseUrl": "https://creativecommons.org/licenses/by-sa/4.0",
    "article": "Marina Bay, Singapore"
  },
  "stb-marina-bay-sands-resort": {
    "url": "https://thumb.wikimedia.org/wikipedia/commons/thumb/c/c7/Marina_Bay_Sands_%28I%29.jpg/960px-Marina_Bay_Sands_%28I%29.jpg?utm_source=commons.wikimedia.org&utm_campaign=imageinfo&utm_content=thumbnail",
    "sourceUrl": "https://commons.wikimedia.org/wiki/File:Marina_Bay_Sands_(I).jpg",
    "author": "This Photo was taken by Supanut Arunoprayote. Feel free to use any of my images, but please mention me as the author and may send me a message. (สามารถใช้ภาพได้อิสระ แต่กรุณาใส่เครดิตผู้ถ่ายและอาจส่งข้อความบอกกล่าวด้วย) Please do not upload an updated image here without consultation with the Author. The author would like to make corrections only at his own source. This ensures that the changes are preserved.Please if you think that any changes should be required, please inform the author.Otherwise you can upload a new image with a new name. Please use one of the templates derivative or extract.",
    "license": "CC BY 4.0",
    "licenseUrl": "https://creativecommons.org/licenses/by/4.0",
    "article": "Marina Bay Sands"
  },
  "stb-chek-jawa": {
    "url": "https://thumb.wikimedia.org/wikipedia/commons/thumb/b/b8/Chek_Jawa_2%2C_Aug_07.JPG/960px-Chek_Jawa_2%2C_Aug_07.JPG?utm_source=commons.wikimedia.org&utm_campaign=imageinfo&utm_content=thumbnail",
    "sourceUrl": "https://commons.wikimedia.org/wiki/File:Chek_Jawa_2,_Aug_07.JPG",
    "author": "Sengkang",
    "license": "CC BY-SA 3.0",
    "licenseUrl": "https://creativecommons.org/licenses/by-sa/3.0",
    "article": "Chek Jawa Visitor Centre"
  },
  "stb-merlion-park-attractions-things-to-do": {
    "url": "https://thumb.wikimedia.org/wikipedia/commons/thumb/8/81/Singapore_Merlion_BCT.jpg/960px-Singapore_Merlion_BCT.jpg?utm_source=commons.wikimedia.org&utm_campaign=imageinfo&utm_content=thumbnail",
    "sourceUrl": "https://commons.wikimedia.org/wiki/File:Singapore_Merlion_BCT.jpg",
    "author": "Bjørn Christian Tørrissen",
    "license": "CC BY-SA 3.0",
    "licenseUrl": "https://creativecommons.org/licenses/by-sa/3.0",
    "article": "Merlion Park"
  },
  "stb-marina-bay-sands-skypark": {
    "url": "https://thumb.wikimedia.org/wikipedia/commons/thumb/c/c7/Marina_Bay_Sands_%28I%29.jpg/960px-Marina_Bay_Sands_%28I%29.jpg?utm_source=commons.wikimedia.org&utm_campaign=imageinfo&utm_content=thumbnail",
    "sourceUrl": "https://commons.wikimedia.org/wiki/File:Marina_Bay_Sands_(I).jpg",
    "author": "This Photo was taken by Supanut Arunoprayote. Feel free to use any of my images, but please mention me as the author and may send me a message. (สามารถใช้ภาพได้อิสระ แต่กรุณาใส่เครดิตผู้ถ่ายและอาจส่งข้อความบอกกล่าวด้วย) Please do not upload an updated image here without consultation with the Author. The author would like to make corrections only at his own source. This ensures that the changes are preserved.Please if you think that any changes should be required, please inform the author.Otherwise you can upload a new image with a new name. Please use one of the templates derivative or extract.",
    "license": "CC BY 4.0",
    "licenseUrl": "https://creativecommons.org/licenses/by/4.0",
    "article": "Marina Bay Sands"
  },
  "stb-resorts-world-sentosa": {
    "url": "https://thumb.wikimedia.org/wikipedia/commons/thumb/3/3f/Resorts_World_Sentosa_viewed_from_the_Singapore_Cruise_Centre_-_20130311.jpg/960px-Resorts_World_Sentosa_viewed_from_the_Singapore_Cruise_Centre_-_20130311.jpg?utm_source=commons.wikimedia.org&utm_campaign=imageinfo&utm_content=thumbnail",
    "sourceUrl": "https://commons.wikimedia.org/wiki/File:Resorts_World_Sentosa_viewed_from_the_Singapore_Cruise_Centre_-_20130311.jpg",
    "author": "Balou46.",
    "license": "CC BY-SA 3.0",
    "licenseUrl": "https://creativecommons.org/licenses/by-sa/3.0",
    "article": "Resorts World Sentosa"
  },
  "stb-sungei-buloh": {
    "url": "https://thumb.wikimedia.org/wikipedia/commons/thumb/c/cb/Sungei_Buloh_Wetland_Reserve_Banner.JPG/960px-Sungei_Buloh_Wetland_Reserve_Banner.JPG?utm_source=commons.wikimedia.org&utm_campaign=imageinfo&utm_content=thumbnail",
    "sourceUrl": "https://commons.wikimedia.org/wiki/File:Sungei_Buloh_Wetland_Reserve_Banner.JPG",
    "author": "Thaejas",
    "license": "CC BY-SA 3.0",
    "licenseUrl": "https://creativecommons.org/licenses/by-sa/3.0",
    "article": "Sungei Buloh Wetland Reserve"
  },
  "stb-singapore-botanic-gardens": {
    "url": "https://thumb.wikimedia.org/wikipedia/commons/thumb/2/24/Symphony_Lake%2C_Singapore_Botanic_Gardens_-_20041025.jpg/960px-Symphony_Lake%2C_Singapore_Botanic_Gardens_-_20041025.jpg?utm_source=commons.wikimedia.org&utm_campaign=imageinfo&utm_content=thumbnail",
    "sourceUrl": "https://commons.wikimedia.org/wiki/File:Symphony_Lake,_Singapore_Botanic_Gardens_-_20041025.jpg",
    "author": "Velela",
    "license": "Public domain",
    "article": "Singapore Botanic Gardens"
  },
  "stb-singapore-zoo-attractions-things-to-do": {
    "url": "https://thumb.wikimedia.org/wikipedia/commons/thumb/5/50/Singapore_Zoo_entrance-15Feb2010.jpg/960px-Singapore_Zoo_entrance-15Feb2010.jpg?utm_source=commons.wikimedia.org&utm_campaign=imageinfo&utm_content=thumbnail",
    "sourceUrl": "https://commons.wikimedia.org/wiki/File:Singapore_Zoo_entrance-15Feb2010.jpg",
    "author": "Drew",
    "license": "CC BY 3.0",
    "licenseUrl": "https://creativecommons.org/licenses/by/3.0",
    "article": "Singapore Zoo"
  },
  "stb-river-safari": {
    "url": "https://thumb.wikimedia.org/wikipedia/commons/thumb/4/46/Crocodile%2C_River_Safari%2C_Singapore_%2824114792687%29.jpg/960px-Crocodile%2C_River_Safari%2C_Singapore_%2824114792687%29.jpg?utm_source=commons.wikimedia.org&utm_campaign=imageinfo&utm_content=thumbnail",
    "sourceUrl": "https://commons.wikimedia.org/wiki/File:Crocodile,_River_Safari,_Singapore_(24114792687).jpg",
    "author": "Romain Pontida",
    "license": "CC BY-SA 2.0",
    "licenseUrl": "https://creativecommons.org/licenses/by-sa/2.0",
    "article": "Commons: Crocodile, River Safari, Singapore (24114792687).jpg"
  },
  "stb-cable-car-singapore-mount-faber": {
    "url": "https://thumb.wikimedia.org/wikipedia/commons/thumb/6/66/Singapore_cable_car_Mount_Faber_1.jpg/960px-Singapore_cable_car_Mount_Faber_1.jpg?utm_source=commons.wikimedia.org&utm_campaign=imageinfo&utm_content=thumbnail",
    "sourceUrl": "https://commons.wikimedia.org/wiki/File:Singapore_cable_car_Mount_Faber_1.jpg",
    "author": "kallerna",
    "license": "CC BY-SA 4.0",
    "licenseUrl": "https://creativecommons.org/licenses/by-sa/4.0",
    "article": "Singapore Cable Car"
  },
  "stb-night-safari": {
    "url": "https://thumb.wikimedia.org/wikipedia/commons/thumb/2/22/Entrance_of_Night_Safari%2C_Singapore%2C_2012.jpg/960px-Entrance_of_Night_Safari%2C_Singapore%2C_2012.jpg?utm_source=commons.wikimedia.org&utm_campaign=imageinfo&utm_content=thumbnail",
    "sourceUrl": "https://commons.wikimedia.org/wiki/File:Entrance_of_Night_Safari,_Singapore,_2012.jpg",
    "author": "Allie Caulfield",
    "license": "CC BY 2.0",
    "licenseUrl": "https://creativecommons.org/licenses/by/2.0",
    "article": "Night Safari, Singapore"
  },
  "stb-little-india-singapore-history-culture": {
    "url": "https://thumb.wikimedia.org/wikipedia/commons/thumb/5/57/Little_India_%284048444495%29.jpg/960px-Little_India_%284048444495%29.jpg?utm_source=commons.wikimedia.org&utm_campaign=imageinfo&utm_content=thumbnail",
    "sourceUrl": "https://commons.wikimedia.org/wiki/File:Little_India_(4048444495).jpg",
    "author": "KimonBerlin",
    "license": "CC BY-SA 2.0",
    "licenseUrl": "https://creativecommons.org/licenses/by-sa/2.0",
    "article": "Little India, Singapore"
  },
  "stb-orchard-road-asia-s-most-famous-shopping-street": {
    "url": "https://thumb.wikimedia.org/wikipedia/commons/thumb/5/59/Presenting..._the_real_ION_%288200217734%29.jpg/960px-Presenting..._the_real_ION_%288200217734%29.jpg?utm_source=commons.wikimedia.org&utm_campaign=imageinfo&utm_content=thumbnail",
    "sourceUrl": "https://commons.wikimedia.org/wiki/File:Presenting..._the_real_ION_(8200217734).jpg",
    "author": "Erwin Soo from Singapore, Singapore",
    "license": "CC BY 2.0",
    "licenseUrl": "https://creativecommons.org/licenses/by/2.0",
    "article": "Orchard Road"
  },
  "stb-macritchie-singapore-singapore-nature-reserve": {
    "url": "https://thumb.wikimedia.org/wikipedia/commons/thumb/e/ee/Info_Board_MacRitchie_Reservoir_Singapore_Feb23_D72_25337.jpg/960px-Info_Board_MacRitchie_Reservoir_Singapore_Feb23_D72_25337.jpg?utm_source=commons.wikimedia.org&utm_campaign=imageinfo&utm_content=thumbnail",
    "sourceUrl": "https://commons.wikimedia.org/wiki/File:Info_Board_MacRitchie_Reservoir_Singapore_Feb23_D72_25337.jpg",
    "author": "This Photo was taken by Timothy A. Gonsalves. Feel free to use my photos, but please mention me as the author. I would much appreciate if you send me an email tagooty@yahoo.com or write on my talk page, for my information. Please contact me before commercial use. Please do not upload an edited image here without consulting me. I would like to make corrections only at my own source to ensure that the changes improve the image and are preserved.Otherwise you may upload an edited image with a new name. Please use one of the templates derivative or extract.",
    "license": "CC BY-SA 4.0",
    "licenseUrl": "https://creativecommons.org/licenses/by-sa/4.0",
    "article": "MacRitchie Reservoir"
  },
  "stb-civic-district": {
    "url": "https://thumb.wikimedia.org/wikipedia/commons/thumb/d/d4/Aerial_view_of_the_Civic_District%2C_Singapore_-_20110224.jpg/960px-Aerial_view_of_the_Civic_District%2C_Singapore_-_20110224.jpg?utm_source=commons.wikimedia.org&utm_campaign=imageinfo&utm_content=thumbnail",
    "sourceUrl": "https://commons.wikimedia.org/wiki/File:Aerial_view_of_the_Civic_District,_Singapore_-_20110224.jpg",
    "author": "William Cho.",
    "license": "CC BY-SA 2.0",
    "licenseUrl": "https://creativecommons.org/licenses/by-sa/2.0",
    "article": "Civic District"
  },
  "stb-harbourfront": {
    "url": "https://thumb.wikimedia.org/wikipedia/commons/thumb/d/db/HarbourFront_Centre_shops_04-12-2024%2824%29.jpg/960px-HarbourFront_Centre_shops_04-12-2024%2824%29.jpg?utm_source=commons.wikimedia.org&utm_campaign=imageinfo&utm_content=thumbnail",
    "sourceUrl": "https://commons.wikimedia.org/wiki/File:HarbourFront_Centre_shops_04-12-2024(24).jpg",
    "author": "LN9267",
    "license": "CC BY-SA 4.0",
    "licenseUrl": "https://creativecommons.org/licenses/by-sa/4.0",
    "article": "Commons: HarbourFront Centre shops 04-12-2024(24).jpg"
  }
};
